package exception

import "errors"

var UserAlreadyExistsError = errors.New("user already exists")
