package exception

import "errors"

var UserNotFoundError = errors.New("user not found")
